# -*- coding: utf-8 -*-
"""papu jsjsj

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pK6o22fPK4ZnuMT63XAcOx359NHE0u0

Hola papu jijiji, mira esto...
"""

import numpy as np
import matplotlib.pyplot as plt

print("si el amor fuese un número entre 500 y 1000...")

xg = st.number_input("¿entre esos números cuanto crees que te amo?: "))

xb = np.linspace((-2),2, int(xg))
fx = np.sqrt(1+(-1)*(np.abs(xb)+(-1))**2)
gx = (-3)*(np.sqrt(1+(-1)*(xb/2)**2))

plt.plot (xb,fx, 'red')
plt.plot(xb, gx, 'red')

plt.title("El corazón de la mamu ❤️")
plt.legend([" este es mi corazon waton"])
plt.show()

if xg < 500:
    print("CABEZON, DIJE SOBRE 500, tan poco crees q te amo¿😢. Yo te amo demasiado mi pete, nunca pienses lo contrario, mua 💘")
elif 1000 > xg > 500:
    print("Jiji eres más pete, yo te amo mucho mas que solo eso mi guañeñiño ❤️ ")
elif xg == 1000:
    print("Jeje, en realidad es una trampa, yo te amo demasiado, tanto que mi corazón esta obeso y no se puede describir solo con números ❤️❤️❤️ ")
elif xg == 500:
  print("papu, como va a ser 500?, no seas tonto, eres lo más lindo que mi corazoncito ha visto en el mundo❤️")
else:
  print("Jeje, es verdad, eres el ser más lindo qye he visto, te amo mucho más que solo un límite como 1000, tanto que ningún número puede definirlo, te amo ❤️❤️❤️")
